// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_json from "rescript/lib/es6/js_json.js";
import * as HyperTypes from "../types/HyperTypes.mjs";
import * as Js_promise from "rescript/lib/es6/js_promise.js";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import NativeHyperswitchSdkReactNative from "../specs/NativeHyperswitchSdkReactNative";

var hyperswitchSdk = NativeHyperswitchSdkReactNative;

function initPaymentSession(initPaymentSessionParams) {
  return hyperswitchSdk.initPaymentSession(initPaymentSessionParams);
}

function presentPaymentSheet(sessionParams) {
  var __x = hyperswitchSdk.presentPaymentSheet(sessionParams);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseResponseFromNativeModule(Core__Option.getOr(Js_json.decodeObject(JSON.parse(result)), {})));
              }), __x);
}

function getCustomerSavedPaymentMethods(sessionParams) {
  var __x = hyperswitchSdk.getCustomerSavedPaymentMethods(sessionParams);
  return Js_promise.then_((function (param) {
                return Promise.resolve(sessionParams);
              }), __x);
}

function getCustomerDefaultSavedPaymentMethodData(sessionParams) {
  var __x = hyperswitchSdk.getCustomerDefaultSavedPaymentMethodData(sessionParams);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseSavedPaymentMethod(Core__Option.getOr(Js_json.decodeObject(result), {})));
              }), __x);
}

function getCustomerLastUsedPaymentMethodData(sessionParams) {
  var __x = hyperswitchSdk.getCustomerLastUsedPaymentMethodData(sessionParams);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseSavedPaymentMethod(Core__Option.getOr(Js_json.decodeObject(result), {})));
              }), __x);
}

function getCustomerSavedPaymentMethodData(sessionParams) {
  var __x = hyperswitchSdk.getCustomerSavedPaymentMethodData(sessionParams);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseAllSavedPaymentMethods(Core__Option.getOr(Js_json.decodeObject(result), {})));
              }), __x);
}

function confirmWithCustomerDefaultPaymentMethod(args) {
  var __x = hyperswitchSdk.confirmWithCustomerDefaultPaymentMethod(args.sessionParams, args.cvc);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseConfirmResponse(Core__Option.getOr(Js_json.decodeObject(result), {})));
              }), __x);
}

function confirmWithCustomerLastUsedPaymentMethod(args) {
  var __x = hyperswitchSdk.confirmWithCustomerLastUsedPaymentMethod(args.sessionParams, args.cvc);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseConfirmResponse(Core__Option.getOr(Js_json.decodeObject(result), {})));
              }), __x);
}

function confirmWithCustomerPaymentToken(args) {
  var __x = hyperswitchSdk.confirmWithCustomerPaymentToken(args.sessionParams, args.cvc, args.paymentToken);
  return Js_promise.then_((function (result) {
                return Promise.resolve(HyperTypes.parseConfirmResponse(Core__Option.getOr(Js_json.decodeObject(result), {})));
              }), __x);
}

export {
  hyperswitchSdk ,
  initPaymentSession ,
  presentPaymentSheet ,
  getCustomerSavedPaymentMethods ,
  getCustomerDefaultSavedPaymentMethodData ,
  getCustomerLastUsedPaymentMethodData ,
  getCustomerSavedPaymentMethodData ,
  confirmWithCustomerDefaultPaymentMethod ,
  confirmWithCustomerLastUsedPaymentMethod ,
  confirmWithCustomerPaymentToken ,
}
/* hyperswitchSdk Not a pure module */
